# Generated by Django 2.1 on 2021-05-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('t_id', models.CharField(max_length=20)),
                ('t_id2', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'db_table': 'Course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StationCodeInfo',
            fields=[
                ('id', models.BigIntegerField(blank=True, null=True)),
                ('requiredConfirmCode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stationCode', models.BigIntegerField(blank=True, null=True)),
                ('orgSaleId', models.CharField(blank=True, max_length=20, null=True)),
                ('stationName', models.CharField(blank=True, max_length=50, null=True)),
                ('towerType', models.CharField(blank=True, max_length=20, null=True)),
                ('roomType', models.CharField(blank=True, max_length=20, null=True)),
                ('towerShareNum', models.IntegerField(blank=True, null=True)),
                ('roomShareNum', models.IntegerField(blank=True, null=True)),
                ('productServiceFee', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('lastTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '订单级管理',
                'db_table': 'StationCodeInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StationInfo',
            fields=[
                ('id', models.BigIntegerField(blank=True, null=True)),
                ('orgSaleId', models.CharField(blank=True, max_length=20, null=True)),
                ('sceneDivide', models.CharField(blank=True, max_length=20, null=True)),
                ('stationName', models.CharField(blank=True, max_length=50, null=True)),
                ('stationNameDx', models.CharField(blank=True, max_length=50, null=True)),
                ('stationCode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stationType', models.CharField(blank=True, max_length=20, null=True)),
                ('stationDetail', models.CharField(blank=True, max_length=255, null=True)),
                ('powerRate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('venueFee', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('demolishTime', models.CharField(blank=True, max_length=20, null=True)),
                ('demolishReason', models.CharField(blank=True, max_length=50, null=True)),
                ('contract', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('lastTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '站址级管理',
                'db_table': 'StationInfo',
                'managed': True,
            },
        ),
    ]
